---
- name: Create resourcegroup
  hosts: localhost
  tasks:
   - name: Create a Resource Group
     azure_rm_resourcegroup:
        name: HackathonTest
        location: Southeast Asia
     register: rg
   - name: Display
     debug:
       var: rg
...
